### ISSUE TITLE
Tracking issue project informatiemodel verkeersborden

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/verkeersborden#238]
# Project 
1.	Analyse modellen en bronnen
- [ ] Een analyse van borden en onderborden in: RVV 1990 en nog geldige borden uit eerdere wetten, IMBOR, en de NWB datasets. 

Inhoudelijke scope Informatiemodel (afwijking op de scope in het [architectuur framework](https://docs.crow.nl/verkeersborden/framework/))
- [ ] Actuele Verkeersborden RVV 1990 met actuele en oude, maar nog rechtsgeldige visualisaties
- [ ] Andere in Nederland voorkomende verkeersborden zonder wettelijke basis, op basis van de dataset van het NDW
- [ ] Tijdelijke verkeersborden
- [ ] Afbeeldingen en teksten op alle actuele gebruikte onderborden, op basis van de dataset van het NDW

2.	Concept-informatiemodel
- [ ] Een concept-informatiemodel 
- [ ] Publicatie en documentatie conform de eisen in [hoofdstuk 12](https://docs.crow.nl/verkeersborden/framework/#samenstelling-informatiemodel) van het architectuur framework 
- [ ] Samenwerking met NLCS om hen te ondersteunen bij het opstellen van visualisatie-afspraken.

3.	Proef-dataset verkeersborden
- [ ] Proef op de som met de dataset van het NDW met verkeersborden en onderborden: NWB dataset met verkeersborden omgezet naar linked data op basis van het informatiemodel (zonder relatie met wegvak/rijbaan/rijstrook). In deze dataset wordt nog niet de relatie gelegd tussen het bord en de geldigheid op een wegvak / rijbaan / rijstrook.

4.	Expert-reviews en openbare consultatie
- [ ] Een openbare consultatie en review door experts middels bijeenkomsten met wegbeheerders, verkeerskundigen, softwareleveranciers en [de werkgroep ISA](https://www.crow.nl/over-crow/nieuws/2023/februari/werkgroep-isa-nederland-coordineert-invoering-snel). 
- [ ] Formeel besluit van de IMBOR Stuurgroep indien wijzigingen aan IMBOR nodig zijn voor het op elkaar aansluiten van de informatiemodellen.

5.	Publicatie informatiemodel
- [ ] Publicatie van en communicatie over de eerste vastgestelde versie van het informatiemodel inclusief een [website](https://docs.crow.nl/verkeersborden/framework/#website).
- [ ] Samenwerking met BZK en NDW om te komen tot een Roadmap voor de komende jaren.

# Buiten scope
In afwijking / aanvulling op het eerder opgestelde [architectuur framework](https://docs.crow.nl/verkeersborden/framework/):
-	Het beheer van het informatiemodel door CROW; hiervoor wordt eind 2024 op verzoek een nieuwe offerte ingediend. Het informatiemodel bevindt zich t/m 2025 in een beproevingsfase, waarbij verwacht wordt dat feedback van gebruikers leidt tot grotere aanpassingen en er hard moet worden gewerkt aan adoptie en implementatie door koplopers. Daarna gaan de beheerlasten omlaag. De kostenindicatie voor het beheer is: in 2024 en 2025 25% van de ontwikkelkosten; daarna 10% van de ontwikkelkosten tot er een grote wettelijke wijziging plaatsvindt van verkeersregels en borden.  Licentiekosten voor beheer- en publicatieplatforms bedragen 10.000 euro per jaar.

-	Het publiceren van de proef-dataset op een linked data platform 

-	NLCS tekenafspraken voor de verkeersborden; verkeersbordenbibliotheek met CAD bouwblokken; Afspraken hoe wijzigingen van CAD naar het NWB te brengen; metadata van IMBOR en van het NWB in de wijzigingsdataset
-	Relateren van de verkeersborden aan het wegennetwerk in de proef-dataset;

Qua inhoud buiten scope, afwijking op de scope in het [architectuur framework](https://docs.crow.nl/verkeersborden/framework/)
-	Verkeersregels conform RVV 1990 in het informatiemodel
-	Wegsoorten, waarschuwingen en adviessnelheden
